Prevent installation of cantera from PyPI
Cantera/conda-recipes pull request #33
Opened 2022-08-09 02:53 UTC by ischoegl

When running `pip install` in `build.sh/.bat`, fetching `cantera` from PyPi needs to be prevented.

Closes #31

There still is an issue with `mkl` on Linux, which can be circumnavigated by also installing `nomkl`.

2022-08-09 03:07 UTC, ischoegl commented
@bryanwweber ... regarding `pytest`, this can now be run as `pytest -vv path/to/samples/python`, but I'm not sure what folder `meta.yaml` runs in.

2022-08-09 15:06 UTC, bryanwweber commented
NumPy pulls in MKL, so that's not totally surprising. I think we'd like to link Cantera to MKL as well, but we can fix that in a separate PR. Thanks for taking this on!

2022-08-09 15:16 UTC, speth approved these changes
Ah, nice job solving the mystery of how this could result in having Cantera 2.6.0 installed. I guess I shouldn't have been surprised that it was a result of `pip` doing something wrong.

2022-08-09 15:22 UTC, ischoegl commented
@bryanwweber ... let me know if you have anything else to add? Won't merge this myself as this is the first time I'm working on this repo.

2022-08-09 23:56 UTC, bryanwweber requested changes
Thanks, a couple of tiny things here

2022-08-09 23:56 UTC, bryanwweber commented on cantera/meta.yaml
> -        - cantera
I don't see a reason to remove this? It's just a very basic check that the package can be imported

2022-08-09 23:56 UTC, bryanwweber commented on cantera/build.sh
> +    # echo "blas_lapack_libs = 'mkl_rt,dl'" >> cantera.conf
Can you add a todo comment here and elsewhere in meta.yaml to note this temporary and that it's commented out to solve #31?

2022-08-10 01:04 UTC, ischoegl commented
@bryanwweber ... thanks! Comments should be taken care of.

2022-08-10 01:37 UTC, bryanwweber approved these changes

2022-08-10 01:37 UTC, merged